### ISSUE TITLE
WorkerPools should have priorities

### ISSUE THREAD

**Issue by bouraqadi** [pharo-contributions/taskit#66]
All workers belonging to the same pool should have the same priority, that can be adapted for all of them at once.

**Comment by bouraqadi** [comment]
Addressed in pull request #67

**Comment by bouraqadi** [comment]
Pull request #68 is the one to use. It fixes a bug.

**Comment by sbragagnolo** [comment]
Thanks for the PR Noury! I am checking it tomorrow :)

**Comment by tinchodias** [comment]
Ah! the PR was merged
