### ISSUE TITLE
TKTDebugger class>>registerToolsOn: broken

### ISSUE THREAD

**Issue by eilx2** [pharo-contributions/taskit#89]
The extension method ToolsRegistry>>registerDebugger:withRank: has been removed in the GT-Debugger package, so this method needs to be fixed.

**Comment by eilx2** [comment]
The most likely fix is just to remove enable/disabled methods and IsEnabled class variable because now all debuggers are available by default in pharo9.

**Comment by tinchodias** [comment]
+1
Loading fails on Pharo 9

**Comment by tinchodias** [comment]
Loading only core avoids the error.

**Comment by tinchodias** [comment]
Ah, I duplicated it in #94

**Comment by tinchodias** [comment]
And PR #95 aims at fixing it.

**Comment by tinchodias** [comment]
Sorry, I will close the original issue and keep the duplicated as to avoid confusion with the PR
