### ISSUE TITLE
TaskIt: TKTRunner and TKTAbstractExecutor should be abstract 

### ISSUE THREAD

**Issue by astares** [pharo-contributions/taskit#93]
port back the changes from https://github.com/pharo-project/pharo/pull/8739
into TaskIt Repo

**Comment by tinchodias** [comment]
@astares 
Now this is done in master. See:
https://github.com/pharo-contributions/taskit/blob/master/TaskIt/TKTRunner.class.st#L50
https://github.com/pharo-contributions/taskit/blob/master/TaskIt/TKTAbstractExecutor.class.st#L19
